sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - COMPOSER_OPTIONS="--prefer-stable"
    - SYMFONY_VERSION=""

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - php: 5.6
    # Test against LTS versions
    - php: 5.6
      env: SYMFONY_VERSION="2.8.x"
    - php: 7.0
      env: SYMFONY_VERSION="3.4.x"
    # Test against dev versions
    - php: 7.1
      env: xdebug=yes COMPOSER_OPTIONS=""

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo memory_limit = -1 >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" && "$xdebug" != "yes" ]]; then phpenv config-rm xdebug.ini; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --dev --no-update; fi

install:
  - composer update $COMPOSER_OPTIONS
  - vendor/bin/simple-phpunit install

script:
  - if [[ "$xdebug" = "yes" ]]; then vendor/bin/simple-phpunit --coverage-clover=coverage.clover; else vendor/bin/simple-phpunit; fi

after_script:
  - if [[ "$xdebug" = "yes" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$xdebug" = "yes" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
